[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solfhe = "CvjJemvL4RD2x1n8smiQ73bTMHwnM4tD2EA54Na5zn9o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
